import { assert, expect, test } from "vitest";
import { parse } from "../src/crust";

test("Crust.parse()", () => {
    const columns = [
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: true,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "s",
            name: "s",
            nullable: 0,
            precision: 20,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -5,
            typeName: "BIGINT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "b",
            name: "b",
            nullable: 1,
            precision: 2,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -7,
            typeName: "BIT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "t",
            name: "t",
            nullable: 1,
            precision: 3,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -6,
            typeName: "TINYINT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "tu",
            name: "tu",
            nullable: 1,
            precision: 3,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -6,
            typeName: "TINYINT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "bo",
            name: "bo",
            nullable: 1,
            precision: 1,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -7,
            typeName: "BIT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "sm",
            name: "sm",
            nullable: 1,
            precision: 5,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 5,
            typeName: "SMALLINT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "smu",
            name: "smu",
            nullable: 1,
            precision: 5,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 5,
            typeName: "SMALLINT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "m",
            name: "m",
            nullable: 1,
            precision: 7,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 4,
            typeName: "MEDIUMINT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "mu",
            name: "mu",
            nullable: 1,
            precision: 8,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 4,
            typeName: "MEDIUMINT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "i",
            name: "i",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 4,
            typeName: "INT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "iu",
            name: "iu",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 4,
            typeName: "INT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "bi",
            name: "bi",
            nullable: 1,
            precision: 19,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -5,
            typeName: "BIGINT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "biu",
            name: "biu",
            nullable: 1,
            precision: 20,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -5,
            typeName: "BIGINT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: true,
            label: "d",
            name: "d",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 3,
            typeName: "DECIMAL",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: false,
            label: "du",
            name: "du",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 3,
            typeName: "DECIMAL UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "f",
            name: "f",
            nullable: 1,
            precision: 12,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 7,
            typeName: "FLOAT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "fu",
            name: "fu",
            nullable: 1,
            precision: 12,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 7,
            typeName: "FLOAT UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: true,
            label: "do",
            name: "do",
            nullable: 1,
            precision: 22,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 8,
            typeName: "DOUBLE",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "dou",
            name: "dou",
            nullable: 1,
            precision: 22,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 8,
            typeName: "DOUBLE UNSIGNED",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "da",
            name: "da",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 91,
            typeName: "DATE",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "dat",
            name: "dat",
            nullable: 1,
            precision: 19,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 93,
            typeName: "DATETIME",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "ti",
            name: "ti",
            nullable: 1,
            precision: 19,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 93,
            typeName: "TIMESTAMP",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "tim",
            name: "tim",
            nullable: 1,
            precision: 10,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 92,
            typeName: "TIME",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: false,
            isCurrency: false,
            isSigned: false,
            label: "y",
            name: "y",
            nullable: 1,
            precision: 4,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 91,
            typeName: "YEAR",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: false,
            label: "v",
            name: "v",
            nullable: 1,
            precision: 32,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 12,
            typeName: "VARCHAR",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: false,
            label: "te",
            name: "te",
            nullable: 1,
            precision: 21845,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -1,
            typeName: "TEXT",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: false,
            label: "e",
            name: "e",
            nullable: 1,
            precision: 1,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: 1,
            typeName: "CHAR",
        },
        {
            arrayBaseColumnType: 0,
            isAutoIncrement: false,
            isCaseSensitive: true,
            isCurrency: false,
            isSigned: false,
            label: "j",
            name: "j",
            nullable: 1,
            precision: 2147483647,
            scale: 0,
            schemaName: "",
            tableName: "reference",
            type: -1,
            typeName: "JSON",
        },
    ];

    const rows = [
        [
            { longValue: 1 },
            { booleanValue: true },
            { longValue: -3 },
            { longValue: 4 },
            { booleanValue: false },
            { longValue: -5 },
            { longValue: 6 },
            { longValue: -7 },
            { longValue: 7 },
            { longValue: -8 },
            { longValue: 8 },
            { longValue: -9 },
            { longValue: 9 },
            { stringValue: "0" },
            { stringValue: "0" },
            { doubleValue: -0.2 },
            { doubleValue: 0.2 },
            { doubleValue: -0.3 },
            { doubleValue: 0.3 },
            { stringValue: "2023-02-24" },
            { stringValue: "2023-02-24 15:17:48" },
            { stringValue: "2023-02-24 15:17:48" },
            { stringValue: "15:17:48" },
            { stringValue: "2023-01-01" },
            { stringValue: "foo" },
            { stringValue: "bar" },
            { stringValue: "A" },
            { stringValue: '{"foo": {"bar": "baz"}}' },
        ],
    ];

    expect(parse(columns, rows)).toBeTypeOf("object");
});
